INSERT INTO TB_ROLE(ROLE_DESC) VALUES ('ROLE_ADMIN');
INSERT INTO TB_ROLE(ROLE_DESC) VALUES ('ROLE_USER');

-- GRUPOS DE INSTRUMENTOS MUSICAIS
INSERT INTO TB_GROUP_INSTRUMENT_MUSICAL VALUES (1, 'Percussão');
INSERT INTO TB_GROUP_INSTRUMENT_MUSICAL VALUES (2, 'Madeiras');
INSERT INTO TB_GROUP_INSTRUMENT_MUSICAL VALUES (3, 'Metais');
INSERT INTO TB_GROUP_INSTRUMENT_MUSICAL VALUES (4, 'Corda');
INSERT INTO TB_GROUP_INSTRUMENT_MUSICAL VALUES (5, 'Teclas');


-- TIPO DE VOZES
INSERT INTO TB_VOICE(NAME) VALUES ('Soprano');
INSERT INTO TB_VOICE(NAME) VALUES ('Mezzo soprano');
INSERT INTO TB_VOICE(NAME) VALUES ('Contralto');
INSERT INTO TB_VOICE(NAME) VALUES ('Tenor');
INSERT INTO TB_VOICE(NAME) VALUES ('Barítonos');
INSERT INTO TB_VOICE(NAME) VALUES ('Baixo');