-- PERCUSSÃO
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Adufe', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Afoxé', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Agogô', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Atabaque', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Batá', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Bateria', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Bloco sonoro', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Bombo', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Bongô', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Caixa Surdo', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Carrilhão', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Castanhola', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Caxixi', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Ceramofone', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Chocalho', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Conga', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Cordofone', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Cuíca', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Ganzá', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Gongo', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Marimba', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Metalofone', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Pandeireta', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Pandeiro', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Pratos', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Reco-reco', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Repinique', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Sino', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Tambor', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Tamborim', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Tantã', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Tímpano', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Triângulo', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Vibrafone', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Xequerê', 1);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Xilofone', 1);


-- MADEIRA
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Clarinete', 2);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Clarone', 2);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Contrafagote', 2);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Corne', 2);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Didjeridu', 2);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Fagote', 2);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Flauta', 2);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Flautim', 2);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Gaita', 2);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Gaita de foles', 2);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Harmônica', 2);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Oboé', 2);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Requinta', 2);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Saxofone', 2);

-- METAIS
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Bombardino', 3);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Clarim', 3);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Corneta', 3);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Fliscorne', 3);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Trombone', 3);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Trompa', 3);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Trompete', 3);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Tuba', 3);

--CORDA
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Alaúde', 4);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Baixo', 4);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Balalaica', 4);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Bandola', 4);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Bandolim', 4);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Banjo', 4);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Berimbau', 4);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Cavaquinho', 4);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Charango', 4);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Cítara', 4);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Contrabaixo', 4);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Cordofone', 4);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Guitarra', 4);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Harpa', 4);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Rabeca', 4);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Ukulele', 4);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Viola', 4);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Violão', 4);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Violino', 4);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Violoncelo', 4);

-- TECLAS
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Acordeão', 5);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Clavicórdio', 5);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Concertina', 5);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Cravo', 5);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Espineta', 5);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Órgão', 5);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Piano', 5);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Sintetizador', 5);
INSERT INTO TB_INSTRUMENT_MUSICAL(NAME, ID_GROUP) VALUES ('Teclado', 5);

