CREATE SEQUENCE EVENT_ID_SEQ MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;

CREATE TABLE IF NOT EXISTS TB_EVENT
(
    ID BIGINT NOT NULL DEFAULT nextval('EVENT_ID_SEQ'),
    ID_BAND BIGINT NOT NULL,
    DATE_EVENT DATE NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    DESC_ADDRESS VARCHAR(255),
    
    CONSTRAINT pk_event primary key (ID),
    FOREIGN KEY (ID_BAND) REFERENCES TB_BAND(ID)
);